[workspace]
resolver = "2"
members = [
    "util",
    "dec1",
    "dec2",
    "dec3",
    "dec4",
    "dec5",
    "dec6",
    "dec7",
    "dec8",
    "dec9",
    "dec10",
    "dec11",
    "dec12",
    "dec13",
    "dec14",
]